name: deploy

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
      - 'release/*'
    paths:
      - ".github/workflows/deploy.yaml"    
      - '*.py'
      - '*.yaml'
      - 'templates/**.html'
      - 'requirements*.txt'

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Deploy
        uses: google-github-actions/deploy-appengine@main
        with:
          credentials: ${{ secrets.GCP_SA_KEY }}

